### ISSUE TITLE
support executing inside AWS CodeBuild

### ISSUE THREAD

**Issue by theburningmonk** [mhart/awscred#2]
When used inside a AWS CodeBuild build environment (which uses ECS under the hood) one needs to use the `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` environment variable and fetch the credentials from `http://169.254.170.2${process.env.AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}`, which returns a payload that looks like this:
```
{  
  "RoleArn": "...",
  "AccessKeyId": "...",
  "SecretAccessKey": "...",
  "Token": "...",
  "Expiration": "2017-12-24T03:14:03Z"
}
```
see [here](https://github.com/swipely/iam-docker/issues/13) for a related question which pointed me to the above URL.

**Comment by mhart** [comment]
Fixed by #3
