### ISSUE TITLE
Support assumed roles in profile INI

### ISSUE THREAD

**Issue by eoinsha** [mhart/awscred#5]
Profile configs in `~/.aws/config` may include a `role_arn` and `source_profile` keys. This specifies that the `source_profile` account should be used to assume the specified role.  (https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)
The feature can be used to support cross-account role access in profiles.

It would be great if `awscred` could uses `STS` to assume the role and derives the access key, id and session token. 

I know this would introduce a (peer) dependency on the AWS SDK. 

I can work on a PR for this but wanted to see if there was any approach recommended first.

**Comment by mhart** [comment]
Yeah, introducing the AWS SDK here kinda goes against the whole idea of this library (which is to be as lightweight as possible).

If you're introducing the AWS SDK, you can probably achieve all that you want solely using that and not need `awscred` at all.

That said, if you want to rework the PR in a way that we can return everything needed to then make the STS call (Possibly add a `roleArn` property, etc to `credentials`? Or return it as a separate top-level property?) – I'd be amenable to that.

**Comment by eoinsha** [comment]
Okay, thanks. I understand the idea. I suppose my goal was to have consistency in the result, so you would have ready-to-use credentials regardless of whether you were using a source profile or assumed role but I can do that outside the module altogether. I'll look at reworking the PR along the lines you suggest.

**Comment by SushilShrestha** [comment]
would like to +1 this feature. I arrive here from the insomnia/postman world where I am using plugin to auto populate the credentials. 
Currently only way I can get the assumed role credential is manual through awscli. I think supporting assume role in awscreds would allow downstream components to rely on awscreds to get the credential from both source profile and assumed role.

Curious if this context would change anything for the assumed role support ?
